import { executeDay1 } from "./src/day-1.js";
import { executeDay2 } from "./src/day-2.js";
import { executeDay3 } from "./src/day-3.js";
import { executeDay4 } from "./src/day-4.js";
import { executeDay5 } from "./src/day-5.js";
import { executeDay6 } from "./src/day-6.js";
import { executeDay7 } from "./src/day-7.js";
import { executeDay8 } from "./src/day-8.js";
import { executeDay9 } from "./src/day-9.js";
import { executeDay10 } from "./src/day-10.js";

// executeDay1();
// executeDay2();
// executeDay3();
// executeDay4();
// executeDay5();
// executeDay6();
// executeDay7();
// executeDay8();
// executeDay9();
executeDay10();